### ISSUE TITLE
Asking about the "DeepACO" paper

### ISSUE THREAD

**Issue by maudzung** [phlong3105/aic22_track4#2]
Hi @phlong3105 
Could you please share your paper `DeepACO: A Robust Deep Learning-based Automatic Checkout System`?

**Comment by longph3105** [comment]
You can find the paper here: https://www.researchgate.net/publication/360560864_DeepACO_A_Robust_Deep_Learning-based_Automatic_Checkout_System

**Comment by maudzung** [comment]
hi @phlong3105 
That's great. Thank you.
